Use the dev branch of ReTestItems in test project
Result:
(DictTools) pkg> test
     Testing DictTools
ERROR: can not merge projects

So this commit causes failure

This commit just changed three lines to point to the dev branch.
modified:   test/Manifest.toml